### ISSUE TITLE
You can add the skin of your choice by renaming the folder.

### ISSUE THREAD

**Issue by singhpawank** [Prayag2/wps-skin-installer#1]
Download the code from this repository. Go to /opt/Kkngsoft/wps-office/office6/skins/. There are two default skins—backup them. Now copy any downloaded skin of your choice to /opt/kingsoft/wps-office/office6/skins/ and rename the folder with default. For example, I copied all-green to /opt/kingsoft/wps-office/office6/skins/ and rename this 2019white. Go to WPS office and choose the 2019white office.

**Comment by Prayag2** [comment]
This is not an issue.

**Comment by singhpawank** [comment]
Yes, this is not an issue but the only solution I found for users not using flatpak.
