### ISSUE TITLE
Missing Pure and Simple themes

### ISSUE THREAD

**Issue by taprobane99** [Prayag2/wps-skin-installer#3]
Hi,

Seems to be missing the 'Pure' and 'Simple' themes from the windows version. Is it possible to add those in?

**Comment by taprobane99** [comment]
ok I guess you have renamed these as Modern and Office-like. maybe keep the original names?

**Comment by Prayag2** [comment]
If you want, you can change the names of their folders in the `.skins` folder and in line 19 of the script. I'll rename them when I get time. Thanks!

**Comment by taprobane99** [comment]
OK. Also, do you know if your repo tracks any updates to the skins? So if Kingsoft decided to tweak one of the skins on Windows/Mac you would be able to put in a new commit on here? that would be nice.

**Comment by Prayag2** [comment]
That's currently not possible for me right now. I copied these themes from
a Windows machine and uploaded them here. I don't know where are these
themes actually hosted on the internet. If you know, then please let me
know!

**Comment by taprobane99** [comment]
I checked one or two and they seem to be identical in number of files, and file size. I was thinking if there was an automatic way of checking but seems not.
